### ISSUE TITLE
Does not compile with node 0.11.9

### ISSUE THREAD

**Issue by Rush** [Southern/node-x509#8]
```
> npm install --save x509
npm WARN package.json x509-test@0.0.0 No description
npm WARN package.json x509-test@0.0.0 No repository field.
npm WARN package.json x509-test@0.0.0 No README data
npm http GET https://registry.npmjs.org/x509
npm http 304 https://registry.npmjs.org/x509

> x509@0.0.7 install /home/rush/Programowanie/x509-test/node_modules/x509
> node-gyp rebuild

make: Entering directory `/home/rush/Programowanie/x509-test/node_modules/x509/build'
  CXX(target) Release/obj.target/x509/src/addon.o
In file included from /home/rush/.node-gyp/0.11.9/src/node.h:61:0,
                 from ../include/addon.h:4,
                 from ../src/addon.cc:4:
/home/rush/.node-gyp/0.11.9/deps/v8/include/v8.h: In member function 'void v8::ReturnValue<T>::Set(uint32_t)':
/home/rush/.node-gyp/0.11.9/deps/v8/include/v8.h:5816:31: warning: typedef 'I' locally defined but not used [-Wunused-local-typedefs]
   typedef internal::Internals I;
                               ^
In file included from ../src/addon.cc:5:0:
../include/x509.h: At global scope:
../include/x509.h:25:36: error: 'Arguments' does not name a type
   Handle<Value> get_altnames(const Arguments &args);
                                    ^
../include/x509.h:25:47: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
   Handle<Value> get_altnames(const Arguments &args);
                                               ^
../include/x509.h:26:35: error: 'Arguments' does not name a type
   Handle<Value> get_subject(const Arguments &args);
                                   ^
../include/x509.h:26:46: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
   Handle<Value> get_subject(const Arguments &args);
                                              ^
../include/x509.h:27:34: error: 'Arguments' does not name a type
   Handle<Value> get_issuer(const Arguments &args);
                                  ^
../include/x509.h:27:45: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
   Handle<Value> get_issuer(const Arguments &args);
                                             ^
../include/x509.h:28:34: error: 'Arguments' does not name a type
   Handle<Value> parse_cert(const Arguments &args);
                                  ^
../include/x509.h:28:45: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
   Handle<Value> parse_cert(const Arguments &args);
                                             ^
../src/addon.cc: In function 'void init(v8::Handle<v8::Object>)':
../src/addon.cc:11:84: error: invalid conversion from 'v8::Handle<v8::Value> (*)(const int&)' to 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}' [-fpermissive]
   exports->Set(String::NewSymbol("getAltNames"), FunctionTemplate::New(get_altnames)->GetFunction());
                                                                                    ^
In file included from /home/rush/.node-gyp/0.11.9/src/node.h:61:0,
                 from ../include/addon.h:4,
                 from ../src/addon.cc:4:
/home/rush/.node-gyp/0.11.9/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of 'static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)' [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
../src/addon.cc:12:82: error: invalid conversion from 'v8::Handle<v8::Value> (*)(const int&)' to 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}' [-fpermissive]
   exports->Set(String::NewSymbol("getSubject"), FunctionTemplate::New(get_subject)->GetFunction());
                                                                                  ^
In file included from /home/rush/.node-gyp/0.11.9/src/node.h:61:0,
                 from ../include/addon.h:4,
                 from ../src/addon.cc:4:
/home/rush/.node-gyp/0.11.9/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of 'static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)' [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
../src/addon.cc:13:80: error: invalid conversion from 'v8::Handle<v8::Value> (*)(const int&)' to 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}' [-fpermissive]
   exports->Set(String::NewSymbol("getIssuer"), FunctionTemplate::New(get_issuer)->GetFunction());
                                                                                ^
In file included from /home/rush/.node-gyp/0.11.9/src/node.h:61:0,
                 from ../include/addon.h:4,
                 from ../src/addon.cc:4:
/home/rush/.node-gyp/0.11.9/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of 'static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)' [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
../src/addon.cc:14:80: error: invalid conversion from 'v8::Handle<v8::Value> (*)(const int&)' to 'v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}' [-fpermissive]
   exports->Set(String::NewSymbol("parseCert"), FunctionTemplate::New(parse_cert)->GetFunction());
                                                                                ^
In file included from /home/rush/.node-gyp/0.11.9/src/node.h:61:0,
                 from ../include/addon.h:4,
                 from ../src/addon.cc:4:
/home/rush/.node-gyp/0.11.9/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of 'static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)' [-fpermissive]
   static Local<FunctionTemplate> New(
                                  ^
make: *** [Release/obj.target/x509/src/addon.o] Error 1
make: Leaving directory `/home/rush/Programowanie/x509-test/node_modules/x509/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rush/.nvm/v0.11.9/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Linux 3.11.6-4-desktop
gyp ERR! command "node" "/home/rush/.nvm/v0.11.9/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rush/Programowanie/x509-test/node_modules/x509
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
npm ERR! x509@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the x509@0.0.7 install script.
npm ERR! This is most likely a problem with the x509 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls x509
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.6-4-desktop
npm ERR! command "/home/rush/.nvm/v0.11.9/bin/node" "/home/rush/.nvm/v0.11.9/bin/npm" "install" "--save" "x509"
npm ERR! cwd /home/rush/Programowanie/x509-test
npm ERR! node -v v0.11.9
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rush/Programowanie/x509-test/npm-debug.log
npm ERR! not ok code 0
```

**Comment by konklone** [comment]
Node did finally stabilize the 0.11 branch as 0.12, and the `x509` module doesn't appear to work there.

**Comment by Rush** [comment]
@konklone you can use my pure-js version https://github.com/encharm/x509.js (built with emscripten)

**Comment by konklone** [comment]
@Rush Nice! Is it fully API-compatible (drop-in)? I'll give it a shot when I'm next at my laptop.

**Comment by yorkie** [comment]
Actually I should cover 0.10, 0.12 and 4.0 into our travis and both they are happy now, so that I'm going to close this one, thanks :)
